/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pawbla_project_home_embedded_sensor_reader_DHTJniReader */

#ifndef _Included_com_pawbla_project_home_embedded_sensor_reader_DHTJniReader
#define _Included_com_pawbla_project_home_embedded_sensor_reader_DHTJniReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pawbla_project_home_embedded_sensor_reader_DHTJniReader
 * Method:    read
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_pawbla_project_home_embedded_sensor_reader_DHTJniReader_read
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
